### ISSUE TITLE
NFL Team Error

### ISSUE THREAD

**Issue by Nwaido15** [boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool#8]
![image](https://github.com/user-attachments/assets/1c98c21b-e8de-41c5-a9f2-799f50c280fb)

Hello, I am getting this error

**Comment by boilermaker-ben** [comment]
Thank you for looking into using the script! You're getting an error because the API for ESPN is either unavailable temporarily or permanently (hopefully not permanently). 

Another user submitted the [same issue](https://github.com/boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool/issues/7#issue-2401047281) a few weeks ago, to which I responded as well. I'll begin updating and revamping this script soon for the 2024 season, and hopefully the ESPN API endpoints will all be functional once the season approaches.
